services:
  mysql:
    image: mysql:latest
    container_name: discord_mysql
    environment:
      MYSQL_ROOT_PASSWORD: discord
      MYSQL_DATABASE: discord
      MYSQL_USER: discord
      MYSQL_PASSWORD: discord
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - discord

volumes:
  mysql_data:
    driver: local

networks:
  discord:
    driver: bridge
